import = ["~/.config/alacritty/themes/kanagawa_wave.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "Monaspace Neon"
style = "Regular"

[font.offset]
x = 0
y = 4

[font.glyph_offset]
x = 0
y = 3

[window.padding]
x = 30
y = 10
