import = ["/home/nikita/.config/alacritty/themes/kanagawa_wave.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "Input Mono"
style = "Regular"


[font.offset]
x = 0
y = 4

[window.padding]
x = 30
y = 10
