import = ["~/.config/alacritty/themes/kanagawa_wave.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "Input Nerd Font"
style = "Regular"

[font.bold]
family = "Input Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Input Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Input Nerd Font"
style = "Italic"

[font.offset]
x = 0
y = 4

[font.glyph_offset]
x = 0
y = 2

[window.padding]
x = 30
y = 10
