require("user.plugins")
require("user.themes.kanagawa")
require("user.options")
require("user.keymaps")
require("user.cmp")
require("user.lsp")
require("user.treesitter")
require("user.blank_indent_highlight")
require("user.autopairs")
require("user.telescope")
require("user.lsp_format")
require("user.bufferline")
require("user.null_ls")
require("user.nvim_scrollbar")
require("user.onedark_config")
require("user.gitsigns")
require("user.lualine")
require("user.dap.dap")
require("user.dap.dapui")
require("user.neotree")
-- require("user.colorschemes.tokyo_night")
-- require("user.nvim_tree")
-- require("user.heirline")

vim.cmd("colorscheme kanagawa")

-- vim.cmd([[highlight IndentBlanklineContextChar guifg=#757575]])
